haproxy_frontends:
  - name: "web"
    mode: "http"
    ports:
      - "*:80"
  - name: "kubernetes-api"
    ports:
      - "*:443"
    mode: "http"

haproxy_backends:
  - name: "kubernetes-api"
    mode: "http"
    options:
      - "httpchk"
      - "log-health-checks"
    httpchecks:
      - "connect"
      - "send meth GET uri /healthz"
      - "expect status 200"
    servers:
      - "master-0 1.1.1.1:6443"
      - "master-1 2.2.2.2:6443"
    servers_opts: "check check-ssl verify none"
  - name: "web"
    mode: "http"
    servers:
      - "web-0 1.1.1.0:80"
      - "web-1 2.2.2.0:80"
